# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: TalkyPipeline

on:
  push:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: checkout
      run: git checkout develop
    - name: install Brew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: install Tuist
      run: curl -Ls https://install.tuist.io | bash
    - name: clean before go through
      run: tuist clean
    - name: tuist fetch
      run: tuist fetch -u
    - name: tuist generate
      run: tuist generate -n
    - name: reset
      run: git reset --hard
    - name: build
      run: xcodebuild build -workspace workspace.xcworkspace -scheme TalkyDev -destination 'platform=iOS Simulator,name=iPhone 14 Plus,OS=latest'
    - name: tests
      run: xcodebuild test -workspace workspace.xcworkspace -scheme TalkyDev -destination 'platform=iOS Simulator,name=iPhone 14 Plus,OS=latest'
